'use client';
import {useMemo,useState} from 'react';
type Tab='overview'|'script'|'shots'|'checklist';
const shots=[['01','中景','固定·平视','陈阿姨接起陌生电话','您好，您的医保账户需要升级。','6s'],['02','特写','俯拍手机','手指准备点击退款链接','请马上点击，否则账户将停用。','5s'],['03','近景','固定·平视','王社工及时走入画面','先别点。陌生链接，不填密码。','7s'],['04','双人中景','固定·侧拍','两人在服务台核实信息','只认官方电话，先核实再操作。','10s'],['05','特写','固定·正拍','醒目的反诈提示卡','不点链接，不说验证码，不转账。','8s']];
export default function Home(){
 const[topic,setTopic]=useState('冒充客服退款诈骗'),[audience,setAudience]=useState('70—79岁 · 中高龄银发'),[duration,setDuration]=useState('60秒'),[actors,setActors]=useState('2人'),[scene,setScene]=useState('社区服务站，手机拍摄，单场景'),[tab,setTab]=useState<Tab>('overview'),[generated,setGenerated]=useState(true),[loading,setLoading]=useState(false);
 const title=useMemo(()=>topic.includes('保健')?'免费鸡蛋背后的陷阱':topic.includes('养老')?'一张卡，办明白养老补贴':'退款电话，先别点',[topic]);
 const generate=()=>{setLoading(true);setGenerated(false);setTimeout(()=>{setLoading(false);setGenerated(true);setTab('overview')},1100)};
 return <main className="shell"><aside className="sidebar"><div className="brand"><span>银</span><div><b>银映 AI</b><small>拍摄方案工作台</small></div></div><nav>{['＋ 新建方案','▤ 方案记录','◇ 银发语料库','◎ 适老规则','✓ 内容审核'].map((x,i)=><button className={i===0?'on':''} key={x}>{x}{i===4&&<em>3</em>}</button>)}</nav><div className="sideFoot"><i/>演示环境运行中<small>知识库更新于 2026-09-06</small></div></aside>
 <section className="workspace"><header className="topbar"><div><span>工作台 / 新建方案</span><h1>AIGC 银发拍摄方案生成器</h1></div><div><button>使用指南</button><b>技</b></div></header><div className="contentGrid">
 <section className="formPanel"><PanelHead step="STEP 01" title="描述这次拍摄任务" extra="草稿已保存"/><label>内容主题<textarea value={topic} onChange={e=>setTopic(e.target.value)}/><small>一句话说明要传达的核心内容</small></label><label>目标银发人群<select value={audience} onChange={e=>setAudience(e.target.value)}><option>55—69岁 · 活力银发</option><option>70—79岁 · 中高龄银发</option><option>80岁及以上 · 高龄银发</option></select></label><div className="two"><label>成片时长<select value={duration} onChange={e=>setDuration(e.target.value)}><option>30秒</option><option>60秒</option><option>90秒</option><option>3分钟</option></select></label><label>演员人数<select value={actors} onChange={e=>setActors(e.target.value)}><option>1人</option><option>2人</option><option>3人</option></select></label></div><label>拍摄条件<textarea value={scene} onChange={e=>setScene(e.target.value)}/></label><label>传播目标<div className="chips"><button className="on">风险提醒</button><button>知识普及</button><button>政策解释</button><button>情感陪伴</button></div></label><div className="source"><span>✓</span><div><b>启用权威知识检索</b><small>生成内容将标注来源并进行风险检查</small></div><i>ON</i></div><button className="generate" onClick={generate} disabled={loading}>{loading?'正在检索与生成…':'✦ 生成拍摄方案'}</button><p className="tip">不会生成视频，仅输出可编辑的文字方案与分镜任务包</p></section>
 <section className="resultPanel"><PanelHead step="STEP 02" title="方案预览" extra={generated?'复制　 导出 ▾':''}/>{!generated?<div className="empty"><strong>✦</strong><h3>正在组合方案</h3><p>检索权威材料、适老化规则与拍摄模板</p><div><i/><i/><i/></div></div>:<><div className="scheme"><div><span>推荐方案</span><h3>{title}</h3><p>{audience} · {duration} · {actors}演员 · 单场景</p></div><div className="score"><b>88</b><span>SilverFit<small>适老评分</small></span></div></div><div className="tabs">{([['overview','方案概览'],['script','完整剧本'],['shots','分镜表  5'],['checklist','拍摄清单']] as [Tab,string][]).map(x=><button key={x[0]} className={tab===x[0]?'on':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div><div className="tabBody">{tab==='overview'&&<Overview topic={topic} scene={scene}/>} {tab==='script'&&<Script title={title}/>} {tab==='shots'&&<Shots/>} {tab==='checklist'&&<Checklist/>}</div></>}</section>
 </div></section></main>}
function PanelHead({step,title,extra}:{step:string,title:string,extra:string}){return <div className="panelHead"><div><span>{step}</span><h2>{title}</h2></div><em>{extra}</em></div>}
function Overview({topic,scene}:{topic:string;scene:string}){return <div className="overview"><section><h4>创意梗概</h4><p>陈阿姨接到一通自称客服的退款电话，正准备点击陌生链接时，社区王社工及时提醒。两人通过官方渠道核实，揭开“退款认证”的骗局，最后总结三个容易记住的反诈动作。</p></section><div className="meta"><div><span>核心信息</span><b>{topic}</b></div><div><span>拍摄条件</span><b>{scene}</b></div></div><h4>SilverFit 适老化检查 <a>查看详情 →</a></h4><div className="fitGrid"><Fit score="92" name="语言可理解性" note="短句为主，无生僻词"/><Fit score="86" name="信息负荷" note="3个关键信息，适中"/><Fit score="90" name="叙事复杂度" note="2人单线叙事"/><Fit score="84" name="视听适老化" note="字幕停留建议≥3秒"/></div><section className="risk"><span>✓</span><div><h4>内容风险审核通过</h4><p>未发现医疗诊断、金融承诺或隐私泄露风险。已匹配 2 条权威来源。</p></div><button>查看来源</button></section></div>}
function Fit({score,name,note}:{score:string;name:string;note:string}){return <div className="fit"><b>{score}</b><div><strong>{name}</strong><small>{note}</small></div><i style={{width:`${score}%`}}/></div>}
function Script({title}:{title:string}){return <div className="script"><h4>《{title}》</h4><p className="scene">场景一 · 社区服务站 · 日 · 内</p><p><b>陈阿姨</b>（看手机）这人说医保账户要升级，还发了个退款链接。</p><p><b>电话声</b> 请马上验证，不然账户就要停用了。</p><p><b>王社工</b>（轻轻拦住）陈阿姨，先别点。陌生链接，不填密码。</p><p><b>陈阿姨</b> 那我怎么知道是不是真的？</p><p><b>王社工</b> 我们只认官方电话，先核实，再操作。</p><p className="caption">【大字字幕】不点陌生链接｜不说验证码｜不向陌生账户转账</p><div className="aiNote">✦ 适老优化：已拆分长句 3 处；关键信息重复 2 次；台词最长 16 字。</div></div>}
function Shots(){return <div className="shotWrap"><table><thead><tr><th>镜号</th><th>景别 / 机位</th><th>画面与动作</th><th>台词</th><th>时长</th></tr></thead><tbody>{shots.map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}<small>{r[2]}</small></td><td>{r[3]}</td><td>{r[4]}</td><td>{r[5]}</td></tr>)}</tbody></table></div>}
function Checklist(){return <div className="checklist"><h4>拍摄任务包</h4><div>{[['人员','陈阿姨（演员1）|王社工（演员1）|拍摄与收音（1人）'],['场地与道具','社区服务站|智能手机 1部|反诈提示卡 1张'],['现场提醒','保持环境安静|手机横向 4K/30fps|台词分段提示'],['后期规范','字幕≥40px|单行不超过14字|重点字幕停留≥3秒']].map(x=><section key={x[0]}><h5>{x[0]}</h5>{x[1].split('|').map(y=><label key={y}><input type="checkbox" defaultChecked/>{y}</label>)}</section>)}</div><button>打印拍摄清单</button></div>}
